project_id = "zytdnqlnsahydanaeupc"

[functions.ai-chat]
verify_jwt = false

[functions.send-risk-alert]
verify_jwt = false

[functions.fetch-blockchain-data]
verify_jwt = false

[functions.voice-chat]
verify_jwt = false

[functions.unified-analyze]
verify_jwt = false

[functions.generate-ai-graph]
verify_jwt = false

[functions.analyze-document]
verify_jwt = false

[functions.send-risk-alert-email]
verify_jwt = false

[functions.analyze-bank-transactions]
verify_jwt = false

[functions.austrac-analyze]
verify_jwt = false