project_id = "zytdnqlnsahydanaeupc"

[functions.ai-chat]
verify_jwt = false

[functions.send-risk-alert]
verify_jwt = false

[functions.fetch-blockchain-data]
verify_jwt = false

[functions.voice-chat]
verify_jwt = false

[functions.generate-visual-report]
verify_jwt = false

[functions.analyze-document]
verify_jwt = false