// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zytdnqlnsahydanaeupc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5dGRucWxuc2FoeWRhbmFldXBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2ODIyNzksImV4cCI6MjA3NDI1ODI3OX0.v3m5dbl3QAQthY-NwEsMtSImWXgoiMBKLp_WTz9-AUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});